services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: agoraespacios_sql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "AgoraDocker123!"
    ports:
      - "1433:1433"
    networks:
      - agoraespaciosnet
    volumes:
      - sqlserver_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agoraespacios_api
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=AgoraEspaciosDb;User Id=sa;Password=AgoraDocker123!;TrustServerCertificate=True"
      Jwt__Key: "JWTKeyDeDesarrollo_123456789_ClaveLarga"
      Frontend__Url: "http://localhost:5173"
      AdminUser__Password: "admin123"
      N8nAdmin__Email: "n8n@agoraespacios.com"
      N8nAdmin__Password: "n8n123"
      N8nAdmin__Nif: "11111111A"
      Swagger__Enabled: "true"
      N8n__ReservaCreadaWebhookUrl: ""
    networks:
      - agoraespaciosnet

volumes:
  sqlserver_data:

networks:
  agoraespaciosnet:
